### ISSUE TITLE
BTK meeting (07/28/21) tasks

### ISSUE THREAD

**Issue by ismael-mendoza** [aboucaud/galcheat#1]
I'm copying here some of the discussion about this that we had during the meeting. Later we can divide it up into more issues, etc. 

- [ ] Link to a website for easy access and visibility
- [x] Take some time to think about exactly which #s we want to use
- [x] Add all surveys from BTK
- [ ] #52
- [ ] #3
- [x] Link to the BTK repo (so people know it was developed as part of BTK)
- [x] #2

**Guiding principles**
- Keep it small so it is easy to plugin by others 
- Not necessarily comprehensive or universal

**Comment by aboucaud** [comment]
Superseeded by the other issues
