### ISSUE TITLE
Decide on a strategy to extend the Survey and Filter classes

### ISSUE THREAD

**Issue by ismael-mendoza** [aboucaud/galcheat#108]
I realized that the way I was coding up BTK to handle adding PSF to filter objects is not possible anymore after #103. Since now 

```
s = get_survey('LSST') 
u = s.get_filter('u') 
u.psf = PSF

u = s.get_filter('u') 
u.psf  # raises an error 
```

Maybe its ok to return a view of filters then ? Or maybe have a more formal setter function? 

```
s.set_value_to_filter('u', 'psf', psf) # would do the same as s.u.psf = psf
u = s.get_filter('u')
u.psf # OK 
```

This makes some sense still since we are now modifying the survey via its own method so it's ok that the filter is now altered.
I'm happy to discuss other ideas @aboucaud, thanks!

**Comment by aboucaud** [comment]
IMO there are two options with advantages and drawbacks

1.  we let `galcheat` classes be mutable
2. we freeze the classes

With option 1. we need a way to make sure the user can always get back on its feet by in the sense that calling `get_survey('Survey').get_filter('filt')` **always** returns the true referenced filter.  This is currently achieved through the view on both the surveys and filters when **and only when** calling `get_survey()` / `get_filter()`. 
The way to obtain modified instances is therefore to either use a "hack" (e.g. `s._filters['u'].psf = PSF` which will modify the filter dictionary and therefore all future calls to `get_filter()` **OR** and this is the preferred way to use BTK's `get_surveys()` to instanciate all surveys and filters and store them modified in a dictionary or custom class.

With option 2., the original `galcheat` classes are safe from modification. The only way to extend them is through inheritance. I checked and it looks quite a simple process:

```python
@dataclass(frozen=True)
 class Surv:
     name: str

class ModSurv(Surv):
     def __setattr__(self, x, val):
         self.__dict__[x] = val

s = Surv('LSST')
s.name = 'DES'   # => FrozenInstanceError: cannot assign to field 'name'

s = ModSurv('LSST')
s.name = 'DES' 
print(s.name)  # => DES
```

Currently we have 1. but switching to 2. might be sensible and maybe easier to explain in the docs.

**Comment by ismael-mendoza** [comment]
I have done some more thinking and perhaps BTK can make without extendable dataclasses for now. I still think option 2. is the way to go in the future. So would definitely at least add `@dataclass(frozen=True)` see  LSSTDESC/BlendingToolKit#285 for more discussion.

**Comment by ismael-mendoza** [comment]
@aboucaud the strategy was implemented in https://github.com/LSSTDESC/BlendingToolKit/pull/289 - if you think this looks good you can close this issue after adding `@dataclass(frozen=True)`
