### ISSUE TITLE
add functions for converting magnitudes to counts, getting noise levels for images, etc.

### ISSUE THREAD

**Issue by beckermr** [aboucaud/galcheat#15]

**Comment by beckermr** [comment]
cc @esheldon

**Comment by aboucaud** [comment]
Sounds like a set of useful functions related to pure survey numbers. Thanks for suggesting :)

You were mentioning that these are already implemented somewhere. Is this in https://github.com/LSSTDESC/WeakLensingDeblending ?

**Comment by beckermr** [comment]
There are functions in there, but IDK if they are correct for the adopted units / conventions here: 

https://github.com/LSSTDESC/WeakLensingDeblending/blob/master/descwl/survey.py#L125

**Comment by beckermr** [comment]
There is also lots of stuff done in the init here: https://github.com/LSSTDESC/WeakLensingDeblending/blob/master/descwl/survey.py#L47

Some of that appears useful.

**Comment by beckermr** [comment]
Maybe this: https://github.com/LSSTDESC/WeakLensingDeblending/blob/master/descwl/survey.py#L110

**Comment by aboucaud** [comment]
Right, so for a given survey you'd like 
- [ ] a method that takes an AB mag and returns the number of counts
- [ ] a method that takes a sky_brightness and returns the `mean_sky_background`
Am I correct ?

**Comment by beckermr** [comment]
@esheldon should confirm, but I think this is the whole thing.
