### ISSUE TITLE
How are the `central wavelengths` seen in Rubin parameters computed ?

### ISSUE THREAD

**Issue by ismael-mendoza** [aboucaud/galcheat#36]
As discussed today, if not really a problem feel free to close this issue.

**Comment by aboucaud** [comment]
@ismael-mendoza as discussed yesterday, please let me know when you manage to find how they were computed

**Comment by aboucaud** [comment]
Do you know what goes into the `throughput` here ?
- filter transmission
- CCD efficiency
- standard atmospheric extinction

**Comment by ismael-mendoza** [comment]
@fjaviersanchez do you know if the central wavelength in WLD accounted for these 3 effects?

**Comment by fjaviersanchez** [comment]
The throughputs that we used had the best estimate available at the time, which include those three components, plus the transmittance of the telescope optics.

**Comment by aboucaud** [comment]
What do you think about renaming it "effective wavelength" ?

**Comment by aboucaud** [comment]
We might use this package to gain useful info on the thoughputs https://bitbucket.org/phosim/phosim_release/wiki/Home

**Comment by mpaillassa** [comment]
I found that the effective wavelength of a filter is embedded in [speclite](https://speclite.readthedocs.io/en/latest/api/speclite.filters.FilterResponse.html#filterresponse) so we may want to use those values here, which would be consistent with the filter zero point values that we also get from speclite. All filter responses of speclite are documented [here](https://speclite.readthedocs.io/en/latest/filters.html).

As you mentioned @aboucaud, we could also use the phosim throughputs but I can't really find where they are coming from ?

**Comment by aboucaud** [comment]
Closing this after successful addition of the speclite values.
