### ISSUE TITLE
Replace effective area with obscuration and compute it

### ISSUE THREAD

**Issue by aboucaud** [aboucaud/galcheat#38]
Please post below the obscuration value for the currently available surveys

**Comment by aboucaud** [comment]
Solved with #43

**Comment by aboucaud** [comment]
Well I managed to add the computation of the effective area inside galcheat using your formula with the obscuration factor.

@mpaillassa you should open a specific PR to modify the values you looked for above for the `mirror_diameter` and `obscuration` since you did all the research.

**Comment by aboucaud** [comment]
@mpaillassa I think you can do this PR right now

**Comment by mpaillassa** [comment]
Yes this is what I intended to do.

**Comment by mpaillassa** [comment]
> From this new reference we can get the obscuration factor for CFHT as 0.20309772 (this is computed using 3.58m mirror diameter so I think we should use this value instead of 3.592m).

Well I may have made a mistake because I do not find back the same value. Going with the information from:

> Axel found another CHFT reference: https://www.cfht.hawaii.edu/Instruments/Imaging/Megacam/specsinformation.html. Section 2.3
> 
> > The CFHT is equiped with a 3.58 diameter mirror and MegaPrime causes an obstruction which is larger than its central hole. After adding the footprint of the primary focus and the four spider branches supporting it, the final collecting area of the primary mirror is 80,216 square centimeters (each spider branch is 5 cm wide, over the area of the primary mirror, 3 are 111.5 cm long and one is 81.5 long, the prime focus can be modeled by two circles of 67.5 cm radius each with a central bridge between their centers of 30 cm).

I find the CFHT obscuration to be 80216/(pi*358*358) = 0.19922557

**Comment by aboucaud** [comment]
Closed by #46
