### ISSUE TITLE
Add gain information

### ISSUE THREAD

**Issue by mpaillassa** [aboucaud/galcheat#39]
Here are information about the gain for each survey:

* CFHT: 1.67 e-/ADU [reference](https://www.cfht.hawaii.edu/Instruments/Imaging/Megacam/generalinformation.html)
* DES: 4 e-/ADU [reference](http://www.ctio.noao.edu/noao/content/DECam-What)
* Euclid_VIS: 3.1 e-/ADU [reference](https://www.mssl.ucl.ac.uk/~smn2/instrument.html)
* HSC: 3e-/ADU [reference](https://www.naoj.org/Observing/Instruments/HSC/parameters.html)
* HST: 1e-/ADU [reference](https://hst-docs.stsci.edu/acsihb/chapter-3-acs-capabilities-design-and-operations/3-5-acs-quick-reference-guide)
* Rubin: I did not find a value. From [here](https://arxiv.org/abs/1907.00995) it seems to be ~0.7-1.0 e-/ADU.

**Comment by aboucaud** [comment]
Hi @mpaillassa, now that the gain is a supported value, you should open a specific PR to add the gain to every survey (YAML file) and link it to this issue.
