### ISSUE TITLE
Make a common reference for speclite zeropoints

### ISSUE THREAD

**Issue by mpaillassa** [aboucaud/galcheat#48]
I realized that we do not have an issue to refer to speclite zeropoints so here it is. Until now the information to make a unified doc for speclite zeropoints was in PR #32. I take it back and reformulate it here.

The zeropoint values of many surveys (HSC, Rubin, DES, Euclid_VIS) come from the [speclite](https://github.com/desihub/speclite) package which uses the official [filter responses](https://speclite.readthedocs.io/en/latest/filters.html#hsc-filters), convolved with a reference magnitude.
At first, we had them in BTK with the WLD convention using a 24 reference magnitude, such that source fluxes can be computed with:
* flux = exp_time * Z_{24} * 10^(-0.4 * (mag-24))

Then, we changed to the more usual convention:
* flux = exp_time * 10^(-0.4 * (mag-Z))

Such that the new zeropoints can be computed from the old ones with:
* Z = (log10(Z_{24}) + 0.4 * 24) / 0.4

This is where our speclite zeropoint values (for HSC, Rubin, DES, Euclid_VIS) are coming from now.

Finally, I would like to point that the computation of the actual zeropoint values from speclite raw values involves the [effective area](https://github.com/LSSTDESC/WeakLensingDeblending/issues/19) of the given telescope. This is why in order to have a clear source of the zeropoint values (and because effective areas may have changed due #46), I think it it would  be nice to have a small piece of code to (re)compute them from speclite and effective areas, rather than relying on WLD values. What do you think ?

**Comment by aboucaud** [comment]
Close by #60
