### ISSUE TITLE
Add small demo for simulating a galaxy using galcheat information

### ISSUE THREAD

**Issue by ismael-mendoza** [aboucaud/galcheat#61]
This was also requested in the BL meeting. Basically a very short script or even just an simple example in the README showing how to actually generate a single galaxy in galsim using the information in the galcheat survey and filter object. Probably after #24 is merged. What do you think @aboucaud ? 

I can definitely create a PR if you think it might be useful since I have to this for BTK anyways.

**Comment by aboucaud** [comment]
Sure, this could either be a short notebook or a short script.
