### ISSUE TITLE
Parameter order and references' names

### ISSUE THREAD

**Issue by mpaillassa** [aboucaud/galcheat#62]
This is not critical and just a reminder to make cleaner and more homogeneous files:
* Have the same parameter order across surveys (e.g., `psf_fwhm` is swapped with `zeropoint` in HSC compared to all other surveys) 
* Have consistency between parameter names in yaml and in the references (e.g., `sky_brightness` is written `sky brightness` in DES references).

**Comment by aboucaud** [comment]
Hi @mpaillassa I can see the first point, but I don't understand what is wrong in the second one. 
I checked the DES.yaml file and `sky_brightness` is written identically as in the other files.

What did I miss ?

**Comment by mpaillassa** [comment]
Yes this is a bit maniac but the second point was about the sky brightness reference in DES where it was written `sky brightness` instead of `sky_brightess` (with the underscore). I made a small PR #94 to change this and some other details I have seen.
